spring:
  application:
    name: auth-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Passw0rd
    initialize: false

server:
  port: 9091
  context-path: /uaa

security:
  sessions: if-required

logging:
  level:
    org: DEBUG



