spring:
  application:
    name: user-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Passw0rd
    initialize: false

server:
  port: 9092

logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

security:
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true #必须要有
      id: user
      user-info-uri: http://auth-server/uaa/user # auth-server 是注册到eureka的服务名称
      prefer-token-info: false



